export const SIGN_IN = 'SIGN_IN';
//Db Users
export const USERS_GETALL = 'USERS_GETALL';
export const USERS_DELETE = 'USERS_DELETE';
export const USERS_GETBYID = 'USERS_GETBYID';
export const USERS_GETFULLINFO = 'USERS_GETFULLINFO';
export const USERS_INSERT = 'USERS_INSERT';
export const USERS_UPDATE = 'USERS_UPDATE';


// Buildings
export const BUILDING_GETALL = 'BUILDING_GETALL';
export const BUILDING_INSERT = 'BUILDING_INSERT';
export const BUILDING_UPDATE = 'BUILDING_UPDATE';
export const BUILDING_DELETE = 'BUILDING_DELETE';

// Producer
export const PRODUCER_GETALL = 'PRODUCER_GETALL';
export const PRODUCER_INSERT = 'PRODUCER_INSERT';
export const PRODUCER_UPDATE = 'PRODUCER_UPDATE';
export const PRODUCER_DELETE = 'PRODUCER_DELETE';

//Reservation
export const RESERVATION_UPDATE = 'RESERVATION_UPDATE';
export const RESERVATION_GETALL = 'RESERVATION_GETALL';
export const RESERVATION_DELETE = 'RESERVATION_DELETE';
export const RESERVATION_RESERVE = 'RESERVATION_RESERVE';

//Washer
export const WASHER_GETALL = 'WASHER_GETALL';
export const WASHER_UPDATE = 'WAHSER_UPDATE';
export const WASHER_DELETE = 'WASHER_DELETE';
export const WASHER_INSERT = 'WASHER_INSERT';

//Room
export const ROOM_GETALL = 'ROOM_GETALL';
export const ROOM_UPDATE = 'ROOM_UPDATE';
export const ROOM_DELETE = 'ROOM_DELETE';
export const ROOM_INSERT = 'ROOM_INSERT';