export const SIGN_IN = 'SIGN_IN';
//Db Users
export const USERS_GETALL = 'USERS_GETALL';
export const USERS_DELETE = 'USERS_DELETE';
export const USERS_GETBYID = 'USERS_GETBYID';
export const USERS_GETFULLINFO = 'USERS_GETFULLINFO';
export const USERS_INSERT = 'USERS_INSERT';
export const USERS_UPDATE = 'USERS_UPDATE';


// Buildings
export const BUILDING_GETALL = 'BUILDING_GETALL';
export const BUILDING_INSERT = 'BUILDING_INSERT';
export const BUILDING_UPDATE = 'BUILDING_UPDATE';
export const BUILDING_DELETE = 'BUILDING_DELETE';

// Producer
export const PRODUCER_GETALL = 'PRODUCER_GETALL';
export const PRODUCER_INSERT = 'PRODUCER_INSERT';
export const PRODUCER_UPDATE = 'PRODUCER_UPDATE';
export const PRODUCER_DELETE = 'PRODUCER_DELETE';